### ISSUE TITLE
Where are the video recording stored ? Do we have any cleanup job to clean the videos after certain interval ?

### ISSUE THREAD

**Issue by samagarw** [sudharsan-selvaraj/appium-dashboard-plugin#105]
Currently we are executing a lot a runs in devices in a day . Can you please let us know where the recording / logs / screenshots are stored for dashboard . Need a job to clean those up after certain interval of time .

**Comment by sudharsan-selvaraj** [comment]
@samagarw In the latest version`2.0.0` we have an ability to delete all session videos and screenshots from the dashboard UI itself with a single click. 

<img width="1725" alt="Screenshot 2022-12-14 at 3 52 20 PM" src="https://user-images.githubusercontent.com/20136913/207569849-3f077975-00ff-475e-8b14-e383b9cc92f4.png">

**Comment by samagarw** [comment]
When this be published  ? I can still see 1.0.0 beta version there .

**Comment by sudharsan-selvaraj** [comment]
I published the new version today. You can run `appium plugin update appium-dashboard --unsafe` to update.

**Comment by duchu** [comment]
@sudharsan-selvaraj It seems to me that it would be good if there was an option to add a parameter that completely disables video recording.

**Comment by sudharsan-selvaraj** [comment]
@duchu Thats sounds valid. I will push a fix with a parameter to disable the video recordings.

**Comment by duchu** [comment]
@sudharsan-selvaraj that would be great. Such a solution in some specific cases can save a lot of disk space. For example, in my tests, the video folder in .cache has ~50GB :)

**Comment by duchu** [comment]
@sudharsan-selvaraj When can we expect fix to be pushed?

**Comment by SushanthN** [comment]
@sudharsan-selvaraj Any update here, do we have a handling to disable video recording

**Comment by sudharsan-selvaraj** [comment]
@SushanthN Use latest version(`2.0.3`) of the plugin and pass `dashboard:enableVideoRecording`: false to disable video recording of the session.
