### ISSUE TITLE
Marking test case status pass or failed . 

### ISSUE THREAD

**Issue by samagarw** [sudharsan-selvaraj/appium-dashboard-plugin#107]
How we can mark the test status in appium dashboard as pass or failed .

**Comment by samagarw** [comment]
Marking session status as passed or failed . Currently it is marking failed even all the tests are passing .

**Comment by samagarw** [comment]
It works thank you . Can you please give me the link for docs for all these ?

**Comment by sudharsan-selvaraj** [comment]
Im still working on creating the proper readme for the project. Will update the links once the changes are ready.
