### ISSUE TITLE
let me know how to make session with appium-dashboard

### ISSUE THREAD

**Issue by tkyoon** [sudharsan-selvaraj/appium-dashboard-plugin#109]
I had install appium 2.0, appium-dashboard
and successfully started appium-dashboard to http://localhost:4723/dashboard/

![image](https://user-images.githubusercontent.com/5343079/209627496-2a8dccc8-8813-4395-bcc5-7cab329991b5.png)

as you see there is no session. so to make session I use appium inspector

like this 

![image](https://user-images.githubusercontent.com/5343079/209627745-246f52ef-7b15-4480-854e-9e15e3c53454.png)

but i can't start session 😭

how can i make the session?

when i start appium server without appium-dashboard, I can start session successfully.

![image](https://user-images.githubusercontent.com/5343079/209628067-3e57448e-0ced-45cd-a2bf-02e657deacf8.png)

please help me.

started appium-dashboard successfully.
![image](https://user-images.githubusercontent.com/5343079/209628413-7f8ea0b5-7b2a-44fd-b6d6-0a4708400598.png)

I can't make session.
![image](https://user-images.githubusercontent.com/5343079/209628492-d358d918-f488-4fda-9f60-2b77bbc7074a.png)

**Comment by sudharsan-selvaraj** [comment]
@tkyoon When you start the appium server manually, the default path would be `/`. If you want to start the server with a different path then you can pass `--base-path /wd/hub` while starting the appium server.

**Comment by tkyoon** [comment]
@sudharsan-selvaraj thank you so much. 
I installed uiautomator2 driver by `appium driver install uiautomator2` and path input /
automationName writed "Uiautomator2"
then i can start session.
![image](https://user-images.githubusercontent.com/5343079/209652778-aae691b9-38e4-47a5-81ac-0682f8fab921.png)

thanks again, have a good day! 😊
