### ISSUE TITLE
My test ran successfully though in appium dashboard that session test result is showing as failed

### ISSUE THREAD

**Issue by Jyothishkumarav** [sudharsan-selvaraj/appium-dashboard-plugin#125]
How are you seeing a session execution test status as passed or failed.  my test cases were passed in a single session. However in dashboard result it is showing as failed.

**Comment by Jyothishkumarav** [comment]
<img width="366" alt="Screenshot 2023-03-09 at 11 48 02 PM" src="https://user-images.githubusercontent.com/19908339/224118964-fc7506a4-a866-4194-8f5a-40e144f488b3.png">
<img width="359" alt="Screenshot 2023-03-09 at 11 47 48 PM" src="https://user-images.githubusercontent.com/19908339/224118983-f4c88fbb-ea73-4a25-8c5e-9a5360689e15.png">

**Comment by sudharsan-selvaraj** [comment]
Currently we don't have a concrete logic to determine if a test execution is pass/fail. We just check all appium commands except `findElement` and `isDisplayed` for any errors. if those commands result in error, we mark those tests as failed. We also provide an option to update the test status from the code.


**Java client:**

```
driver.executeScript("dashboard: updateStatus", ImmutableMap.of("status", "passed"));
```

**Webdriver.IO:**

```
driver.executeScript("dashboard: updateStatus", [{status: "passed"}]);
```

**Comment by Jyothishkumarav** [comment]
Thanks for the update

**Comment by Jyothishkumarav** [comment]
I have tried with above code, but getting below response from appium server. i am using python appium client 
      driver.execute_script("dashboard: updateStatus", '''[{"status": "passed"}]''')

`Calling AppiumDriver.execute() with args: ["dashboard: updateStatus",["[{\"status\": \"passed\"}]"],"2e7e7af9-bd05-40db-acf7-aba6ffa1ee95"]
[AppiumDriver@20f6] Plugins which can handle cmd 'execute': appium-dashboard
[AppiumDriver@20f6] Plugin appium-dashboard is now handling cmd 'execute'
[AppiumDriver@20f6] Command 'execute' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["appium-dashboard"].
[debug] [AndroidUiautomator2Driver@497f (2e7e7af9)] Responding to client with driver.execute() result: true`

**Comment by sudharsan-selvaraj** [comment]
Can you try using `driver.execute_script("dashboard: updateStatus", '''{"status": "passed"}''')`?
