### ISSUE TITLE
Configure a Docker volume to preserve the information of the test session

### ISSUE THREAD

**Issue by win5923** [sudharsan-selvaraj/appium-dashboard-plugin#126]
I am using appium-docker-android and install the Appium Dashboard plugin. I would like to know where the detailed information of each session is stored because every time I restart, the data of the test session disappears. I want to set up a Docker volume to ensure that my test data and video records do not disappear. Can you tell me how to set it up? Thank you.

**Comment by sudharsan-selvaraj** [comment]
The default location where the data and videos will be stored is under
1. Mac `/Users/<username>/.cache/appium-dashboard-plugin`
2. Linux `/home/<username>/.cache/appium-dashboard-plugin`

You can mount the above directory as a volume to hostmachine while starting the docker container. Refer [stackoverflow](https://stackoverflow.com/questions/23439126/how-to-mount-a-host-directory-in-a-docker-container) thread for more details on docker mounting.

**Comment by win5923** [comment]
*  Executing task: docker logs --tail 1000 -f 5b14c9682c5df3420a79ed4cca84e6fadf5a9b3335d17fa9a753011d5b091bb4 

Prepare adb to have access to device
* daemon not running; starting now at tcp:5037
* daemon started successfully
adb can be used now
[Appium] Attempting to load plugin appium-dashboard...
[debug] [Appium] Requiring plugin at /home/androidusr/.appium/node_modules/appium-dashboard
[ADB] Found 1 'build-tools' folders under '/opt/android' (newest first):
[ADB]     /opt/android/build-tools/33.0.0
[ADB] Using 'adb' from '/opt/android/platform-tools/adb'
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 start-server'
[Appium] Welcome to Appium v2.0.0-beta.57
[Appium] Non-default server args:
[Appium] { allowCors: true,
[Appium]   relaxedSecurityEnabled: true,
[Appium]   usePlugins: [ 'appium-dashboard', 'device-farm' ] }
[Appium] Attempting to load driver espresso...
[debug] [Appium] Requiring driver at /home/androidusr/.appium/node_modules/appium-espresso-driver
[Appium] Attempting to load driver flutter...
[debug] [Appium] Requiring driver at /home/androidusr/.appium/node_modules/appium-flutter-driver
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at /home/androidusr/.appium/node_modules/appium-uiautomator2-driver
[appium-dashboard] Dashboard plugin is enabled and will be served at http://localhost:4723/dashboard
[appium-dashboard] If the appium server is started with different port other than 4723, then use the correct port number to access the device farm dashboard
(node:34) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[Appium] You have enabled CORS requests from any host. Be careful not to visit sites which could maliciously try to start Appium sessions on your machine
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - espresso@2.20.1 (automationName 'Espresso')
[Appium]   - flutter@1.14.3 (automationName 'Flutter')
[Appium]   - uiautomator2@2.14.0 (automationName 'UiAutomator2')
[Appium] Available plugins:
[Appium]   - appium-dashboard@v2.0.2 (ACTIVE)
uncaughtException: SQLITE_CANTOPEN: unable to open database file
SequelizeConnectionError: SQLITE_CANTOPEN: unable to open database file
    at Database.<anonymous> (/home/androidusr/.appium/node_modules/appium-dashboard/node_modules/sequelize/src/dialects/sqlite/connection-manager.js:78:34)


can't mount the above directory as a volume to hostmachine.

**Comment by win5923** [comment]
same problem.i already changed the permission on the host.
