### ISSUE TITLE
Readme: To add instructions for users migration from 1.X to 2.0 - since 2.0 has breaking changes and without help some users may be frustrated post migration. 

### ISSUE THREAD

**Issue by PramodKumarYadav** [sudharsan-selvaraj/appium-dashboard-plugin#6]
Although your plugin scope should not bother about migration from 1.X to 2.0 however there are breaking changes in 2.0 and when most users will try to install 2.0 to try your awesome plugin, they will find that there stable tests don't run anymore. 

Thus although helping users with migration should not really be a concern for your plugin, adding those instructions will help new users to easily be able to use your plugin without feeling lost due to 2.0 breaking changes. 

Two such breaking changes that I encountered while migrating were:
One) -> To run this command `appium -pa /wd/hub --plugins=appium-dashboard` instead of just this command `appium   --plugins=appium-dashboard`, if your base URL contains /wd/hub (which it should for 1/X) and which is now not supported in appium 2.0.
https://github.com/appium/appium/issues/15261
Two) -> The existing appium capabilities are not supported in 2.0 and there are a couple of workarounds users would need to do to be able to run their existing projects in 2.0 and use your dashboard. These are listed here: https://appiumpro.com/editions/123-migrating-to-appium-20-part-1-capability-prefixes

Do let me know what you think about these suggestions? 

P.S: On other note, if you like, I can be a contributor to your awesome project and give not just suggestions but also create PRs with solutions. If you like this idea, do ping me on linkedin and I will be happy to contribute where I can :). I am also working on a new open source project which is first of its kind and if you like, I would be happy to have you as a contributor :). Cheers!

**Comment by saikrishna321** [comment]
IMO migration details with specific to Appium 2.0 should not be a concern to this plugin. Main Appium repo has migration docs in place already. Folks who move from 1.x to 2.x should refer to the official migration.
