### ISSUE TITLE
failed to create session: nativeWebScreenshot should not exist on primary and secondary

### ISSUE THREAD

**Issue by cparello** [sudharsan-selvaraj/appium-dashboard-plugin#67]
1. caps
{
  "appium:automationName": "Appium",
  "appium:orientation": "PORTRAIT",
  "platformName": "Android",
  "appium:platformVersion": "10",
  "appium:deviceName": "emulator-5554",
  "appium:appPackage": "ccom.android.vending",
  "appium:appActivity": "com.google.android.finsky.activities.MainActivity"
}

node 14.19
I get the error in the title when running via the appium inspector

2. if i run the same test via node with the same caps i get "enviroment unavailible unknown server side error, cannot read property firstMatch of undefined.
3. If i kill appium server and run with no plugin the test works fine.

**Comment by sudharsan-selvaraj** [comment]
@cparello Looks like a valid issue. I will be fixing it in the upcoming release.

**Comment by sudharsan-selvaraj** [comment]
Fixed as part of `v1.0.0-beta.13`
