### ISSUE TITLE
Installation error of the plugin

### ISSUE THREAD

**Issue by ravibabu101143** [sudharsan-selvaraj/appium-dashboard-plugin#84]
I tried to install the plugin but failed.  I have attached log. Can you help on this as i want to use it along with device farm.
[2022-09-02T14_16_25_384Z-debug-0.log](https://github.com/sudharsan-selvaraj/appium-dashboard-plugin/files/9478595/2022-09-02T14_16_25_384Z-debug-0.log)

appium plugin install --source=npm appium-dashboard

**Comment by sudharsan-selvaraj** [comment]
@ravibabu101143 Installation of `sqlite` module is causing the issue. Can you try with nodejs version 17 and see if the installation works?

**Comment by ravibabu101143** [comment]
Thank you Sudharsan. I upgraded to nodejs to stable version v16.7.0, i guess at least it installed the plugin..

√ Installing 'appium-dashboard'
‼ Plugin "appium-dashboard" has 1 potential problem:
  - Plugin "appium-dashboard" (package `appium-dashboard`) may be incompatible with the current version of Appium (v2.0.0-beta.43) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-dashboard` to add a peer dependency on `^appium@2.0.0-beta.43`.
i Plugin appium-dashboard@v1.0.0-beta.14 successfully installed

**Comment by ravibabu101143** [comment]
After nodejs updation.it is working fine for me. Thanks @sudharsan-selvaraj
