### ISSUE TITLE
Problem with latest appium 2.0@b46

### ISSUE THREAD

**Issue by duchu** [sudharsan-selvaraj/appium-dashboard-plugin#88]
When i want to start appium server with device-farm and this plugin, console throws this message and shutdown

`WARN Appium   - Plugin "appium-dashboard" (package `appium-dashboard`) may be incompatible with the current version of Appium (v2.0.0-beta.46) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-dashboard` to add a peer dependency on `^appium@2.0.0-beta.46`.`

@sudharsan-selvaraj do you have plans to update your plugin in near future?

**Comment by macro-dadt** [comment]
having the same issue

**Comment by sudharsan-selvaraj** [comment]
@duchu  Fixed the issue as part of **v2.0.0**. Update the plugin using below command 

`appium plugin update appium-dashboard --unsafe`
